In [1]:
import pandas as pd
from scipy.stats.stats import pearsonr
import numpy as np
import scipy.stats as s
import seaborn as sns
from matplotlib import pyplot as plt

In [2]:
original_dataset = pd.read_csv("./datasets/tumor_data")

In [3]:
#for checking null values in any column
original_dataset.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed:

In [4]:
labels = original_dataset['diagnosis']

In [5]:
X = original_dataset.iloc[:,2:32]
X

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     concavity_worst  concave points_worst  symmetry_worst  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

In [6]:
X_dash = X-X.mean()

In [7]:
X_dash.shape

(569, 30)

In [8]:
X_dash = np.array(X_dash)

In [9]:
X_dash

array([[ 3.86270826e+00, -8.90964851e+00,  3.08309666e+01, ...,
         1.50793777e-01,  1.70024429e-01,  3.49541828e-02],
       [ 6.44270826e+00, -1.51964851e+00,  4.09309666e+01, ...,
         7.13937768e-02, -1.50755712e-02,  5.07418278e-03],
       [ 5.56270826e+00,  1.96035149e+00,  3.80309666e+01, ...,
         1.28393777e-01,  7.12244288e-02,  3.63418278e-03],
       ...,
       [ 2.47270826e+00,  8.79035149e+00,  1.63309666e+01, ...,
         2.71937768e-02, -6.82755712e-02, -5.74581722e-03],
       [ 6.47270826e+00,  1.00403515e+01,  4.81309666e+01, ...,
         1.50393777e-01,  1.18624429e-01,  4.00541828e-02],
       [-6.36729174e+00,  5.25035149e+00, -4.40490334e+01, ...,
        -1.14606223e-01, -2.97557118e-03, -1.35558172e-02]])

In [10]:
p = X_dash.shape[0]

In [53]:
# sigma_dash=np.cov(X_Dash,rowvar=0)
sigma_dash=(1/p)*np.matmul(X_dash.T,X_dash)
sigma_dash.shape

(30, 30)

In [54]:
factorized_matrices = np.linalg.svd(sigma_dash)

In [55]:
Q = factorized_matrices[0]
Q.shape

(30, 30)

In [56]:
data = np.array(X)

In [57]:
def PCAed_data(data,variance_to_preserve):
    
    global L
    L=1
    eig_values_total = np.sum(factorized_matrices[1])
    
    eig_values_sum = 0
    
    for eig_val in factorized_matrices[1]:
        
        if eig_values_sum/eig_values_total >= variance_to_preserve:
            
            break
            
            
        eig_values_sum = eig_values_sum + eig_val
            
        L = L + 1
            
    M = factorized_matrices[0][:,0:L]
    
    print(M.shape)
    print(L)
    return np.matmul(data,M)

In [58]:
reduced_data = PCAed_data(data,0.99999999)

(30, 15)
15


In [59]:
reduced_data_cov = np.cov(reduced_data,rowvar=0)
reduced_data_cov.shape

(15, 15)

In [60]:
np.linalg.det(reduced_data_cov)

283.23171629140535

In [61]:
working_reduced_data = pd.DataFrame(data=reduced_data)

In [62]:
working_reduced_data

0           1          2          3          4          5  \
0   -2260.013886 -187.960301  17.912961  77.262942  54.129246  16.565625   
1   -2368.993756  121.587424 -66.059971  50.689683  17.793886  18.056912   
2   -2095.665202  145.113986 -32.375189  64.351626  21.662230  20.483851   
3    -692.690510   38.576923 -21.992589  80.310834  29.244221  16.531604   
4   -2030.212493  295.297984 -29.290636  60.051784  29.742049  16.809879   
..           ...         ...        ...        ...        ...        ...   
564 -2513.997996  216.179735   9.400507  61.988726  17.025903  18.226464   
565 -2144.890167  183.014831 -30.628768  73.304212   9.710897  17.890677   
566 -1414.373069  153.510768 -41.107844  78.322848  15.972547  18.701766   
567 -2224.729428  140.086467 -50.407524  92.211848  25.693893  13.744650   
568  -328.343691   17.314136  -6.776405  66.003718   7.411193  13.412917   

            6         7         8         9        10        11        12  \
0    3.404070  0.356151  0.982284  1.570398  1.142613 -0.548187  0.316680   
1    2.426695  0.303514  2.213575  0.897004  0.754167 -0.537777  0.327388   
2    1.692988  0.778344  1.901621  0.794045  0.555635 -0.484271  0.365408   
3    1.205428  0.564873  2.058385  0.836884 -0.092662 -0.330015  0.564459   
4    2.137210  0.215210  1.691659  0.842537  0.792581 -0.442014  0.167655   
..        ...       ...       ...       ...       ...       ...       ...   
564  1.685982  0.467236  2.180276  0.745854  0.671159 -0.557278  0.206871   
565  2.922563 -0.004836  2.177732  1.474285  0.827184 -0.560567  0.266739   
566  0.306240  0.946597  1.825145  0.836371  0.943956 -0.580997  0.277454   
567  0.767331  0.864282  1.342717  1.596506  0.527643 -0.476511  0.342464   
568 -0.343020  0.474279  2.151198  0.679600  0.701456 -0.389630  0.262235   

           13        14  
0   -0.372683  0.004145  
1   -0.302081 -0.030157  
2   -0.332439  0.018098  
3   -0.387672 -0.051990  
4   -0.309888  0.010759  
..        ...       ...  
564 -0.292404  0.052601  
565 -0.317600 -0.012101  
566 -0.252329  0.003670  
567 -0.269873  0.023084  
568 -0.321348 -0.004655  

[569 rows x 15 columns]

In [63]:
working_reduced_data['labels']= labels

In [64]:
working_reduced_data

0           1          2          3          4          5  \
0   -2260.013886 -187.960301  17.912961  77.262942  54.129246  16.565625   
1   -2368.993756  121.587424 -66.059971  50.689683  17.793886  18.056912   
2   -2095.665202  145.113986 -32.375189  64.351626  21.662230  20.483851   
3    -692.690510   38.576923 -21.992589  80.310834  29.244221  16.531604   
4   -2030.212493  295.297984 -29.290636  60.051784  29.742049  16.809879   
..           ...         ...        ...        ...        ...        ...   
564 -2513.997996  216.179735   9.400507  61.988726  17.025903  18.226464   
565 -2144.890167  183.014831 -30.628768  73.304212   9.710897  17.890677   
566 -1414.373069  153.510768 -41.107844  78.322848  15.972547  18.701766   
567 -2224.729428  140.086467 -50.407524  92.211848  25.693893  13.744650   
568  -328.343691   17.314136  -6.776405  66.003718   7.411193  13.412917   

            6         7         8         9        10        11        12  \
0    3.404070  0.356151  0.982284  1.570398  1.142613 -0.548187  0.316680   
1    2.426695  0.303514  2.213575  0.897004  0.754167 -0.537777  0.327388   
2    1.692988  0.778344  1.901621  0.794045  0.555635 -0.484271  0.365408   
3    1.205428  0.564873  2.058385  0.836884 -0.092662 -0.330015  0.564459   
4    2.137210  0.215210  1.691659  0.842537  0.792581 -0.442014  0.167655   
..        ...       ...       ...       ...       ...       ...       ...   
564  1.685982  0.467236  2.180276  0.745854  0.671159 -0.557278  0.206871   
565  2.922563 -0.004836  2.177732  1.474285  0.827184 -0.560567  0.266739   
566  0.306240  0.946597  1.825145  0.836371  0.943956 -0.580997  0.277454   
567  0.767331  0.864282  1.342717  1.596506  0.527643 -0.476511  0.342464   
568 -0.343020  0.474279  2.151198  0.679600  0.701456 -0.389630  0.262235   

           13        14 labels  
0   -0.372683  0.004145      M  
1   -0.302081 -0.030157      M  
2   -0.332439  0.018098      M  
3   -0.387672 -0.051990      M  
4   -0.309888  0.010759      M  
..        ...       ...    ...  
564 -0.292404  0.052601      M  
565 -0.317600 -0.012101      M  
566 -0.252329  0.003670      M  
567 -0.269873  0.023084      M  
568 -0.321348 -0.004655      B  

[569 rows x 16 columns]

In [65]:
# getting e class training data for getting the......
# PRIOR PROBABILITY of target variable CLASS 'b'

b_reduced_data = working_reduced_data[working_reduced_data['labels']== 'B']
b_reduced_data

0           1          2          3          4          5  \
19  -908.250267  118.216420 -36.906456  64.962933  28.821481  17.868536   
20  -814.820038  120.514604 -40.843408  67.067952  27.957540  18.621514   
21  -416.287360   73.381116 -15.570094  55.974186  23.836021  16.726566   
37  -743.993463  167.492809 -36.908222  63.580876  19.052688  19.581990   
46  -316.032645   49.130686 -17.007567  57.621305  15.015819  15.088430   
..          ...         ...        ...        ...        ...        ...   
558 -974.626177  184.380675 -45.824641  74.618827  21.779765  19.177160   
559 -620.535606  101.579369 -27.588866  77.001252  10.972141  17.774022   
560 -922.628497  149.680386 -32.276958  78.319286  15.006065  20.267088   
561 -581.859450  104.426388 -19.073113  76.197219   4.319294  18.993100   
568 -328.343691   17.314136  -6.776405  66.003718   7.411193  13.412917   

            6         7         8         9        10        11        12  \
19   2.809725  0.663820  1.714031  0.991425  0.913012 -0.541245  0.252632   
20   2.553273  0.958790  1.459506  1.073539  0.867177 -0.382402  0.318908   
21   2.162737  0.176306  1.592283  0.748412  0.795009 -0.491070  0.265114   
37   2.381482 -0.007450  1.625116  1.992842  0.858923 -0.564112  0.281578   
46   1.725235  0.751670  1.382233  0.747926  0.754052 -0.409137  0.290978   
..        ...       ...       ...       ...       ...       ...       ...   
558  1.004048  0.617297  1.204529  0.920572  0.933189 -0.537429  0.246883   
559  5.362358 -0.374080  1.409306  1.374280  0.802179 -0.604447  0.209205   
560  0.970259  0.413905  1.784563  0.743723  1.021172 -0.480999  0.315284   
561  2.031073 -0.613017  1.763559  2.353375  0.815677 -0.504733  0.282539   
568 -0.343020  0.474279  2.151198  0.679600  0.701456 -0.389630  0.262235   

           13        14 labels  
19  -0.346960 -0.025912      B  
20  -0.307220 -0.026466      B  
21  -0.299961  0.001883      B  
37  -0.289551 -0.043999      B  
46  -0.334743 -0.015544      B  
..        ...       ...    ...  
558 -0.248617 -0.034263      B  
559 -0.241892 -0.026800      B  
560 -0.255219 -0.013331      B  
561 -0.221134 -0.049706      B  
568 -0.321348 -0.004655      B  

[357 rows x 16 columns]

In [66]:
# getting e class training data for getting the......
# PRIOR PROBABILITY of target variable CLASS 'm'
m_reduced_data =working_reduced_data[working_reduced_data['labels']== 'M']
m_reduced_data

0           1          2          3          4          5  \
0   -2260.013886 -187.960301  17.912961  77.262942  54.129246  16.565625   
1   -2368.993756  121.587424 -66.059971  50.689683  17.793886  18.056912   
2   -2095.665202  145.113986 -32.375189  64.351626  21.662230  20.483851   
3    -692.690510   38.576923 -21.992589  80.310834  29.244221  16.531604   
4   -2030.212493  295.297984 -29.290636  60.051784  29.742049  16.809879   
..           ...         ...        ...        ...        ...        ...   
563 -2267.008290  211.553922 -19.563363  82.754470  29.486187  15.006264   
564 -2513.997996  216.179735   9.400507  61.988726  17.025903  18.226464   
565 -2144.890167  183.014831 -30.628768  73.304212   9.710897  17.890677   
566 -1414.373069  153.510768 -41.107844  78.322848  15.972547  18.701766   
567 -2224.729428  140.086467 -50.407524  92.211848  25.693893  13.744650   

            6         7         8         9        10        11        12  \
0    3.404070  0.356151  0.982284  1.570398  1.142613 -0.548187  0.316680   
1    2.426695  0.303514  2.213575  0.897004  0.754167 -0.537777  0.327388   
2    1.692988  0.778344  1.901621  0.794045  0.555635 -0.484271  0.365408   
3    1.205428  0.564873  2.058385  0.836884 -0.092662 -0.330015  0.564459   
4    2.137210  0.215210  1.691659  0.842537  0.792581 -0.442014  0.167655   
..        ...       ...       ...       ...       ...       ...       ...   
563 -0.658235 -0.456995  0.938589  0.305679  1.274293 -0.529561  0.155994   
564  1.685982  0.467236  2.180276  0.745854  0.671159 -0.557278  0.206871   
565  2.922563 -0.004836  2.177732  1.474285  0.827184 -0.560567  0.266739   
566  0.306240  0.946597  1.825145  0.836371  0.943956 -0.580997  0.277454   
567  0.767331  0.864282  1.342717  1.596506  0.527643 -0.476511  0.342464   

           13        14 labels  
0   -0.372683  0.004145      M  
1   -0.302081 -0.030157      M  
2   -0.332439  0.018098      M  
3   -0.387672 -0.051990      M  
4   -0.309888  0.010759      M  
..        ...       ...    ...  
563 -0.361934 -0.003929      M  
564 -0.292404  0.052601      M  
565 -0.317600 -0.012101      M  
566 -0.252329  0.003670      M  
567 -0.269873  0.023084      M  

[212 rows x 16 columns]

$$\text{Naive Bayes Classifier}\$$

\begin{equation}
P(A|B) = \frac{P(B|A)*P(A)}{P(B)}
\end{equation}
\
\
\begin{equation}
\text{P(target var|feature var)} = \frac{\text{P(feature var|target var) * P(target var)}}{\text{P(feature var)}}
\end{equation}
\
\
\begin{equation}
P(A|B1,B2,B3,B4.......Bn) = \frac{P(B1|A)*P(B2|A)*P(B3|A) ...*P(Bn|A)*P(A)}{P(B1)*P(B2)*P(B3) *....*P(Bn)}
\end{equation}

\
\
\begin{equation}
\text{P( target var|feature var1, feature var2, feature var3, ... ,feature var(n) )} = \frac{\text{P(feature var1|target var) * P(feature var2|target var) * P(feature var3|target var) *...* P(feature var(n)|target var) * P(target var)}}{\text{P(feature var1) * P(feature var2) * P(feature var3) *...* P(feature var(n)}}
\end{equation}

\begin{equation}
\text{Posterior Probability}\\\text{P(A|B1,B2,B3.......Bn)}\\
\text{P( target var|feature var1, feature var2, feature var3, ... ,feature var(n) )}
\end{equation}

\begin{equation}
\text{Likelihood probability}\\\text{P(B1|A) * P(B2|A) * P(B3|A) *...* P(Bn|A)}\\
\text{P(feature var1|target var) * P(feature var2|target var) * P(feature var3|target var) *...* P(feature var(n)|target var)}
\end{equation}

\begin{equation}
\text{Prior Probability}\\ \text{P(A)}\\
\text{P(target var)}
\end{equation}

\begin{equation}
\text{Evidence or Normalizing Probability }\\
{P(B1)*P(B2)*P(B3) *....*P(Bn)}\\
\text{P(feature var1) * P(feature var2) * P(feature var3) *...* P(feature var(n))}
\end{equation}

\begin{equation}
\text{Prior Probability}\\ \text{P(A) => P(class='e')}
\end{equation}

In [67]:
mean_for_M = np.array(m_reduced_data.iloc[:,0:L].mean())
mean_for_M

array([-1.73300456e+03,  1.01644461e+02, -3.39751752e+01,  7.18518374e+01,
        2.26318451e+01,  1.77857083e+01,  2.56459256e+00,  4.97301963e-01,
        1.76217359e+00,  9.62301635e-01,  7.82826260e-01, -5.02638228e-01,
        2.81777930e-01, -3.12236380e-01, -7.51104330e-03])

In [68]:
mean_for_B = np.array(b_reduced_data.iloc[:,0:L].mean())
mean_for_B

array([-7.23893025e+02,  1.08518334e+02, -2.86999893e+01,  6.65907856e+01,
        2.18300085e+01,  1.78579595e+01,  2.41818272e+00,  5.08484554e-01,
        1.70730281e+00,  9.92165493e-01,  8.65678100e-01, -5.05979649e-01,
        2.81976298e-01, -3.04869969e-01, -9.54776771e-03])

In [69]:
sigma_for_M = np.array(m_reduced_data.iloc[:,0:L].cov())
sigma_for_M

array([[ 4.78991266e+05,  5.91580704e+03, -6.48989083e+03,
         3.87313407e+03,  1.35500329e+03,  1.69993352e+02,
         1.72945470e+02,  5.63153755e+01,  6.57881576e+01,
        -9.58596674e+00, -3.14004056e+01, -2.86910692e+00,
         3.07454616e-01, -2.35065361e+00,  7.59709273e-01],
       [ 5.91580704e+03,  1.73723992e+04,  4.86609331e+02,
        -9.22953325e+00, -1.16360190e+02, -5.56828362e+01,
        -6.22945597e+00, -7.10526240e+00, -3.11677907e-02,
        -3.47430441e+00, -4.33158856e+00,  1.15190615e+00,
        -2.97438497e-01, -2.73834197e-01,  1.00298441e-01],
       [-6.48989083e+03,  4.86609331e+02,  1.63017440e+03,
         2.88922352e+01,  3.55966807e+01,  6.39104150e+00,
         7.47507609e+00,  7.01942997e+00,  3.93880427e-02,
        -1.84512008e-02,  1.02294242e+00, -2.27813772e-01,
         4.33586486e-02,  8.90060226e-02, -2.00501704e-01],
       [ 3.87313407e+03, -9.22953325e+00,  2.88922352e+01,
         8.20945514e+01,  1.97264726e+01, -1.39074128

In [70]:
sigma_for_B = np.array(b_reduced_data.iloc[:,0:L].cov())
sigma_for_B

array([[ 4.36913615e+04, -6.09796578e+03,  1.85760983e+03,
        -3.11995945e+02, -5.00785863e+02, -1.27995680e+02,
        -4.73026485e+01, -3.75941549e+01, -1.83042483e+01,
        -5.57813186e+00, -1.26270797e+01,  2.96034071e+00,
        -2.57018709e-01, -1.38416607e+00,  3.17638054e-01],
       [-6.09796578e+03,  1.34908921e+03, -3.01959895e+02,
         1.89821983e+01,  7.10256383e+01,  3.28174675e+01,
         4.06819988e+00,  4.18254499e+00,  1.59396886e-01,
         1.98250959e+00,  2.35453073e+00, -6.74149166e-01,
         1.75781330e-01,  1.43381555e-01, -5.42156574e-02],
       [ 1.85760983e+03, -3.01959895e+02,  1.46374597e+02,
        -6.75496534e+00, -1.95176382e+01, -3.93035359e+00,
        -4.14188328e+00, -4.18243301e+00,  8.48033883e-02,
        -4.79247454e-02, -7.69592852e-01,  1.41610289e-01,
        -2.60895010e-02, -6.72725309e-02,  1.22851003e-01],
       [-3.11995945e+02,  1.89821983e+01, -6.75496534e+00,
         2.81936225e+01, -1.32679738e+01,  9.66310953

In [71]:
np.linalg.det(sigma_for_B)

1.8887968816835275e-06

In [72]:
np.linalg.det(sigma_for_M)

18329.68573968481

It's not a bug. It's not an incorrect result either. Probability density function's value at some specific point does not give you probability; it is a measure of how dense the distribution is around that value. For continuous random variables, the probability at a given point is equal to zero. Instead of p(X = x), we calculate probabilities between 2 points p(x1 < X < x2) and it is equal to the area below that probability density function. Probability density function's value can very well be above 1. It can even approach to infinity.

\begin{equation}
\text{Posterior Probability}\\\text{P(A|B1,B2,B3.......Bn)}\\
\text{P( target var|feature var1, feature var2, feature var3, ... ,feature var(n) )}
\end{equation}

\begin{equation}
\text{Likelihood probability}\\\text{P(B1|A) * P(B2|A) * P(B3|A) *...* P(Bn|A)}\\
\text{P(feature var1|target var) * P(feature var2|target var) * P(feature var3|target var) *...* P(feature var(n)|target var)}
\end{equation}

\begin{equation}
\text{Prior Probability}\\ \text{P(A)}\\
\text{P(target var)}
\end{equation}

\begin{equation}
\text{Evidence or Normalizing Probability }\\
{P(B1)*P(B2)*P(B3) *....*P(Bn)}\\
\text{P(feature var1) * P(feature var2) * P(feature var3) *...* P(feature var(n))}
\end{equation}

$$\text{Posterior Probability} = \frac{\text{Likelihood Probability} * \text{Prior Probability}}{\text{Normalizing Probability}}$$

$$\text{P( target var|feature var1, feature var2, feature var3, ... ,feature var(n) )} = \frac{\text{P(feature var1|target var) * P(feature var2|target var) * P(feature var3|target var) *...* P(feature var(n)|target var) * P(target var)}}{\text{P(feature var1) * P(feature var2) * P(feature var3) *...* P(feature var(n)}}$$

In [73]:
# for getting the relative frequency of the values in the particular column in the dataset
def relative_frequency(dataset,column):
    frequency = dataset[column].value_counts()
    rf = np.array(frequency)/dataset.shape[0]
    rf_column = dict(zip(frequency.keys(),rf))
    return rf_column
#     return {column : {k: v for k,v in zip(frequency,frequency/training_data.shape[0])}}

In [74]:
target_frequency = relative_frequency(working_reduced_data,'labels')
target_frequency

{'B': 0.6274165202108963, 'M': 0.37258347978910367}

In [75]:
training_prior_prob_b = target_frequency['B']
training_prior_prob_m = target_frequency['M']
print(training_prior_prob_b,training_prior_prob_m)

0.6274165202108963 0.37258347978910367


In [76]:
def predicted_category(single_row):
    
    likelihood_m = s.multivariate_normal.pdf(single_row,mean=mean_for_M,cov=sigma_for_M)
    likelihood_b = s.multivariate_normal.pdf(single_row,mean=mean_for_B,cov=sigma_for_B)
    
    numerator = likelihood_m * training_prior_prob_m
    
    dinominator = numerator + (likelihood_b * training_prior_prob_b)
    
    posterior_m = numerator/dinominator
    
    return np.uint(posterior_m > 0.5)

In [77]:
working_reduced_data

0           1          2          3          4          5  \
0   -2260.013886 -187.960301  17.912961  77.262942  54.129246  16.565625   
1   -2368.993756  121.587424 -66.059971  50.689683  17.793886  18.056912   
2   -2095.665202  145.113986 -32.375189  64.351626  21.662230  20.483851   
3    -692.690510   38.576923 -21.992589  80.310834  29.244221  16.531604   
4   -2030.212493  295.297984 -29.290636  60.051784  29.742049  16.809879   
..           ...         ...        ...        ...        ...        ...   
564 -2513.997996  216.179735   9.400507  61.988726  17.025903  18.226464   
565 -2144.890167  183.014831 -30.628768  73.304212   9.710897  17.890677   
566 -1414.373069  153.510768 -41.107844  78.322848  15.972547  18.701766   
567 -2224.729428  140.086467 -50.407524  92.211848  25.693893  13.744650   
568  -328.343691   17.314136  -6.776405  66.003718   7.411193  13.412917   

            6         7         8         9        10        11        12  \
0    3.404070  0.356151  0.982284  1.570398  1.142613 -0.548187  0.316680   
1    2.426695  0.303514  2.213575  0.897004  0.754167 -0.537777  0.327388   
2    1.692988  0.778344  1.901621  0.794045  0.555635 -0.484271  0.365408   
3    1.205428  0.564873  2.058385  0.836884 -0.092662 -0.330015  0.564459   
4    2.137210  0.215210  1.691659  0.842537  0.792581 -0.442014  0.167655   
..        ...       ...       ...       ...       ...       ...       ...   
564  1.685982  0.467236  2.180276  0.745854  0.671159 -0.557278  0.206871   
565  2.922563 -0.004836  2.177732  1.474285  0.827184 -0.560567  0.266739   
566  0.306240  0.946597  1.825145  0.836371  0.943956 -0.580997  0.277454   
567  0.767331  0.864282  1.342717  1.596506  0.527643 -0.476511  0.342464   
568 -0.343020  0.474279  2.151198  0.679600  0.701456 -0.389630  0.262235   

           13        14 labels  
0   -0.372683  0.004145      M  
1   -0.302081 -0.030157      M  
2   -0.332439  0.018098      M  
3   -0.387672 -0.051990      M  
4   -0.309888  0.010759      M  
..        ...       ...    ...  
564 -0.292404  0.052601      M  
565 -0.317600 -0.012101      M  
566 -0.252329  0.003670      M  
567 -0.269873  0.023084      M  
568 -0.321348 -0.004655      B  

[569 rows x 16 columns]

In [78]:
validation_data_rows =np.array(working_reduced_data.iloc[:,0:L])

In [79]:
validation_data_rows

array([[-2.26001389e+03, -1.87960301e+02,  1.79129612e+01, ...,
         3.16679856e-01, -3.72683290e-01,  4.14495750e-03],
       [-2.36899376e+03,  1.21587424e+02, -6.60599707e+01, ...,
         3.27387884e-01, -3.02080752e-01, -3.01570660e-02],
       [-2.09566520e+03,  1.45113986e+02, -3.23751894e+01, ...,
         3.65407724e-01, -3.32438780e-01,  1.80983441e-02],
       ...,
       [-1.41437307e+03,  1.53510768e+02, -4.11078436e+01, ...,
         2.77454004e-01, -2.52329345e-01,  3.67006640e-03],
       [-2.22472943e+03,  1.40086467e+02, -5.04075239e+01, ...,
         3.42463649e-01, -2.69872657e-01,  2.30844805e-02],
       [-3.28343691e+02,  1.73141361e+01, -6.77640455e+00, ...,
         2.62235452e-01, -3.21348475e-01, -4.65476659e-03]])

In [80]:
validation_predicted_answers = []

In [81]:
validation_predicted_answers = predicted_category(validation_data_rows)
    

In [82]:
validation_predicted_answers = np.array(validation_predicted_answers)
validation_predicted_answers

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,

In [83]:
working_reduced_data

0           1          2          3          4          5  \
0   -2260.013886 -187.960301  17.912961  77.262942  54.129246  16.565625   
1   -2368.993756  121.587424 -66.059971  50.689683  17.793886  18.056912   
2   -2095.665202  145.113986 -32.375189  64.351626  21.662230  20.483851   
3    -692.690510   38.576923 -21.992589  80.310834  29.244221  16.531604   
4   -2030.212493  295.297984 -29.290636  60.051784  29.742049  16.809879   
..           ...         ...        ...        ...        ...        ...   
564 -2513.997996  216.179735   9.400507  61.988726  17.025903  18.226464   
565 -2144.890167  183.014831 -30.628768  73.304212   9.710897  17.890677   
566 -1414.373069  153.510768 -41.107844  78.322848  15.972547  18.701766   
567 -2224.729428  140.086467 -50.407524  92.211848  25.693893  13.744650   
568  -328.343691   17.314136  -6.776405  66.003718   7.411193  13.412917   

            6         7         8         9        10        11        12  \
0    3.404070  0.356151  0.982284  1.570398  1.142613 -0.548187  0.316680   
1    2.426695  0.303514  2.213575  0.897004  0.754167 -0.537777  0.327388   
2    1.692988  0.778344  1.901621  0.794045  0.555635 -0.484271  0.365408   
3    1.205428  0.564873  2.058385  0.836884 -0.092662 -0.330015  0.564459   
4    2.137210  0.215210  1.691659  0.842537  0.792581 -0.442014  0.167655   
..        ...       ...       ...       ...       ...       ...       ...   
564  1.685982  0.467236  2.180276  0.745854  0.671159 -0.557278  0.206871   
565  2.922563 -0.004836  2.177732  1.474285  0.827184 -0.560567  0.266739   
566  0.306240  0.946597  1.825145  0.836371  0.943956 -0.580997  0.277454   
567  0.767331  0.864282  1.342717  1.596506  0.527643 -0.476511  0.342464   
568 -0.343020  0.474279  2.151198  0.679600  0.701456 -0.389630  0.262235   

           13        14 labels  
0   -0.372683  0.004145      M  
1   -0.302081 -0.030157      M  
2   -0.332439  0.018098      M  
3   -0.387672 -0.051990      M  
4   -0.309888  0.010759      M  
..        ...       ...    ...  
564 -0.292404  0.052601      M  
565 -0.317600 -0.012101      M  
566 -0.252329  0.003670      M  
567 -0.269873  0.023084      M  
568 -0.321348 -0.004655      B  

[569 rows x 16 columns]

In [84]:
#for converting the column_values to unique number 
def converstion(dataset,column_name):
    unique_values = dataset[column_name].unique().tolist()
    unique_values.sort()
    convert = {column_name : {k: v for k,v in zip(unique_values,list(range(0,len(unique_values))))}}
    dataset.replace(convert,inplace=True)

In [85]:
converstion(working_reduced_data,'labels')

In [86]:
working_reduced_data.shape[0]

569

In [87]:
validation_actual_answers = np.array(working_reduced_data['labels'])
validation_actual_answers

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,

In [88]:
validation_correct_count = np.count_nonzero(validation_predicted_answers == validation_actual_answers)
validation_correct_count

545

In [89]:
validation_correct_count/working_reduced_data.shape[0]

0.9578207381370826

In [90]:
validation_accuracy = (validation_correct_count/working_reduced_data.shape[0])*100

In [91]:
validation_accuracy

95.78207381370825

In [92]:
confusion_matrix = pd.crosstab(validation_predicted_answers,validation_actual_answers, colnames= ['actual'], rownames = ['predicted'], margins = True)

In [93]:
confusion_matrix

actual       0    1  All
predicted               
0          349   16  365
1            8  196  204
All        357  212  569

In [94]:
TP = confusion_matrix[0][0]
print('True Positive',TP)
TN = confusion_matrix[1][1]
print('True Negative',TN)
FP = confusion_matrix[0][1]
print('False Positive',FP)
FN = confusion_matrix[1][0]
print('False Negative',FN)

True Positive 349
True Negative 196
False Positive 8
False Negative 16
